PetShop/Areas/Admin/Controllers/ProfessionalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetShop_Business.Exceptions;
using PetShop_Business.Services.Abstracts;
using PetShop_Core.Models;
using FileNotFoundException = PetShop_Business.Exceptions.FileNotFoundException;

namespace PetShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProfessionalController : Controller
    {
        private readonly IProfessionalService _professionalService;

        public ProfessionalController(IProfessionalService professionalService)
        {
            _professionalService = professionalService;
        }

        public IActionResult Index()
        {
            List<Professional> professionals = _professionalService.GetAllProfessionals();
            return View(professionals);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Professional professional)
        {
            if(!ModelState.IsValid)
                return View();

            try
            {
                _professionalService.AddProfessional(professional);
            }
            catch(NullReferenceException ex)
            {
                return NotFound();
            }
            catch(FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ImageNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var existProfessional = _professionalService.GetProfessional(x => x.Id == id);
            if(existProfessional == null)
                return NotFound();

            try
            {
                _professionalService.DeleteProfesional(id);
            }
            catch (EntityNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(FileNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }


            return RedirectToAction(nameof(Index));

        }

        public IActionResult Update(int id)
        {
            var existProfessional = _professionalService.GetProfessional(x => x.Id == id);
            if (existProfessional == null)
                return NotFound();

            return View(existProfessional);
        }

        [HttpPost]
        public IActionResult Update(int id, Professional professional)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                _professionalService.UpdateProfesional(id, professional);
            }
            catch (NullReferenceException ex)
            {
                return NotFound();
            }
            catch (FileContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (EntityNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (ImageNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (FileNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

PetShop/Areas/Admin/Views/Professional/Create.cshtml
@using PetShop_Core.Models;
@model Professional


<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-3">
                <label asp-for="Fullname" class="form-label">Fullname</label>
                <input asp-for="Fullname" class="form-control" >
                <span asp-validation-for="Fullname" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="ImgFile" class="form-label">ImgFile</label>
                <input asp-for="ImgFile" class="form-control">
                <span asp-validation-for="ImgFile" style="color:red"></span>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 col-md-9">
                <label asp-for="Description" class="form-label">Description</label>
                <textarea asp-for="Description" class="form-control"  rows="3"></textarea>
                <span asp-validation-for="Description" style="color:red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>

PetShop/Areas/Admin/Views/Professional/Index.cshtml
@using PetShop_Core.Models;
@model List<Professional>

@{
    int count = 0;
}

<h1>
    Professionals

    <a class="btn btn-primary" asp-action="Create">Create</a>
</h1>

<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    count++;
                    <tr>
                    <td>@count</td>
                    <td>@item.Fullname</td>
                    <td>@item.Description</td>
                    <td>
                        <div style="width:100px">
                            <img width="100%" src="~/upload/professional/@item.ImgUrl" />
                        </div>
                    </td>

                    <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="Professional" asp-route-id="@item.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Professional" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PetShop/Areas/Admin/Views/Professional/Update.cshtml
@using PetShop_Core.Models;
@model Professional


<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-3">
                <label asp-for="Fullname" class="form-label">Fullname</label>
                <input asp-for="Fullname" class="form-control">
                <span asp-validation-for="Fullname" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="ImgFile" class="form-label">Image</label>
                <input asp-for="ImgFile" class="form-control">
                <span asp-validation-for="ImgFile" style="color:red"></span>
            </div>
        </div>
        <div class="row">
            <div class="mb-3 col-md-9">
                <label asp-for="Description" class="form-label">Description</label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" style="color:red"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>